const initial = {
  tab: 'home', drawer: false, completed: [0], day: 18, automation: 'ASSIST', visualVariant: 0,
  posts: [
    { text: 'はじめました。\nたぶんすぐ消すかも。', purpose: '初投稿｜プロフィールへの導線', time: 'DAY 1 20:30', status: 'published', type: '自己紹介' },
    { text: 'やっと帰宅。\n今日、思ったより長かった。', purpose: 'DAY 18｜認知をファン化へつなぐ', time: '今夜 20:30', status: 'approval', type: '日常' }
  ],
  messages: [{ from:'bot', text:'DAY 18です。いまは「見られることが嬉しい」段階。数字を追わせすぎず、帰宅後に小さな楽しみができたことを投稿で見せましょう。' }]
};
const state = JSON.parse(localStorage.getItem('aoba-x-operator-v2') || 'null') || initial;
const save = () => localStorage.setItem('aoba-x-operator-v2', JSON.stringify(state));
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tasks = [['朝投稿を確認','08:00｜仕事前の短い一言'],['見込みユーザーを見る','12:30｜日常系アカウントを10件'],['夜投稿を作る','20:30｜帰宅後の自然な一枚']];
const phase = [['設計',100],['認知',68],['ファン化',31],['販売',0]];
const visualPrompts = [
  { title:'本命｜帰宅後の鎧がほどける瞬間', reason:'直近で強い「仕事帰り」「全身が分かる」「短い弱音」を維持しつつ、前回と構図を変える案です。', text:'30代前半の日本人女性、華奢な体型、鎖骨に触れるダークブラウンのミディアムヘア。夜の1Kマンション、白い壁、薄い木目の床。帰宅直後、濃紺の仕事用ジャケットを片手で脱ぎながら、もう片方の手で髪を右耳にかける途中。白いブラウス、チャコールグレーのタイトスカート、黒いパンプス。営業用ではない、少し疲れて緊張がほどけた自然な表情。部屋の暖色の間接照明、スマートフォンで偶然撮られたような生活感のある縦長写真、9:16、自然な肌、過度な演出や性的強調なし。' },
  { title:'テスト｜休日の余白を見せる一枚', reason:'認知の反応を保ったまま、ファン化に必要な「職場以外のあおば」を1本だけ試す案です。', text:'30代前半の日本人女性、鎖骨に触れるダークブラウンのミディアムヘア、片側を耳にかけている。休日の午後、駅近くの静かな歩道。白いシャツ、淡いブルーのデニム、白いスニーカー、小さな黒い革トート。歩きながら誰かの言葉に思わず笑った直後、作り込まない自然な表情。やわらかい曇り空の光、少し後れ毛、遠くに街路樹。通りすがりに撮ったような日常の縦長写真、9:16、現実的な質感、ポーズを決めすぎない、過度な性的強調なし。' },
  { title:'予備｜反応を休ませる静かな夜', reason:'毎回「見せる」写真に寄りすぎないための、物語の余白を作る案です。', text:'30代前半の日本人女性、ダークブラウンの髪を低い位置でゆるくまとめている。夜の1Kマンション、グレーのソファに浅く座り、黒いパンプスを脱いだ直後。無地のグレーTシャツ、脇に黒い仕事用バッグ、テーブルの上に飲み切れていない水とコンビニのプリン。横を向き、少しだけ眉間の力が残る疲れた表情。室内の暖色照明、静かで現実的な生活写真、縦長9:16、映画的にしすぎない、過度な性的強調なし。' }
];
function copyText(text){if(navigator.clipboard?.writeText){navigator.clipboard.writeText(text).catch(()=>fallbackCopy(text));}else{fallbackCopy(text);}}
function fallbackCopy(text){const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();document.execCommand('copy');area.remove();}
function header(title, desc='') { return `<header class="top"><div class="brand">AOBA / X OPERATOR</div><div class="top-actions"><div class="day">DAY ${state.day}</div><button class="menu-btn" data-action="drawer" aria-label="メニュー">☰</button></div></header><h1 class="title">${title}</h1>${desc?`<p class="sub">${desc}</p>`:''}`; }
function drawer() { if (!state.drawer) return ''; const items=[['home','全体ダッシュボード','今日の運用'],['progress','裏アカの進捗','4フェーズ'],['character','アカウント作成','キャラクター・世界観'],['posts','ポスト','下書き・投稿キュー'],['schedule','週間スケジュール','次の7日'],['engage','交流','リプ候補・返信'],['monetize','note・販売','商品化・ローンチ'],['analytics','分析→改善','次週へ反映'],['guide','設計指針','運用ルール']]; return `<section class="card"><p class="eyebrow">OPERATOR MENU</p>${items.map(x=>`<button class="list-link" data-go="${x[0]}"><span><b>${x[1]}</b><small>${x[2]}</small></span><span>›</span></button>`).join('')}</section>`; }
function home(){ return header('今日の運用','キャラクター、物語、数値を一つの流れで動かします。')+drawer()+`<section class="hero"><p class="eyebrow">CURRENT STORY · DAY 18–21</p><h2 style="margin:0;font-size:22px">見られることが嬉しい</h2><p class="caption">仕事以外に、帰宅後の小さな楽しみができはじめた頃。</p><div class="score-row"><div class="score"><span class="caption">Followers</span><b>184</b></div><div class="score"><span class="caption">Affinity</span><b>35</b></div><div class="score"><span class="caption">Story</span><b>58%</b></div></div></section><section class="card"><p class="eyebrow">OPERATING LOOP</p><div class="flow">${phase.map((p,i)=>`<button class="${i===1?'current':''}" data-go="progress">0${i+1}<br><b>${p[0]}</b><br>${p[1]}%</button>`).join('')}</div></section><section class="card"><p class="eyebrow">TODAY · あと ${3-state.completed.length} TASK</p>${tasks.map((t,i)=>`<div class="task ${state.completed.includes(i)?'done':''}"><button data-task="${i}" class="check">${state.completed.includes(i)?'✓':''}</button><div class="task-main">${t[0]}<small>${t[1]}</small></div>${i===2?'<button data-go="create">作る</button>':''}</div>`).join('')}</section><section class="card"><p class="eyebrow">AI ADVICE</p><div class="advice">昨日の「仕事帰り＋全身が分かる写真」はプロフィール訪問率が高めでした。今日は構図を変え、<b>部屋で髪をほどく途中</b>のような、薄い鎧が外れる瞬間を続けます。</div><button class="primary" data-go="create">今日の投稿を作る</button></section>`; }
function progress(){return header('認知から販売まで','一本道ではなく、4つの能力を同時に育てます。')+drawer()+`<section class="card"><p class="eyebrow">PHASE MAP</p>${phase.map((p,i)=>`<div class="bar-row"><b>0${i+1} ${p[0]}</b><div class="bar"><i style="width:${p[1]}%"></i></div><span>${p[1]}%</span></div>`).join('')}<p class="callout">現在の主フェーズは<strong>認知</strong>。反応の良い文脈を保ちながら、キャラクターへの理解を積み上げます。</p></section><section class="card"><p class="eyebrow">NEXT MISSION</p><b>固定投稿と初期9投稿を完成させる</b><p class="sub">フォローする理由が、名前・アイコン・プロフィール・固定投稿から一貫して伝わる状態にします。</p><button class="secondary" data-go="character">アカウント設計を確認</button></section>`;}
function character(){return header('アカウント設計','設定資料ではなく、すべての投稿判断に使う運用エンジンです。')+drawer()+`<section class="card"><p class="eyebrow">IDENTITY · 100%</p><b>あおば｜33歳｜不動産会社勤務</b><p class="sub">仕事中は背筋を伸ばす。帰宅すると肩が内側へ落ちる。整えることで自分を守っている。</p></section><section class="card"><p class="eyebrow">EMOTIONAL CORE · 100%</p><p class="callout">役に立たなくても、自分には価値があると思いたい。</p><p class="sub">会社から解放されるために始めたSNSでも、再び「期待される自分」を演じてしまうことが最大の葛藤です。</p></section><section class="card"><p class="eyebrow">VISUAL & CONTENT RULES</p><p class="sub">濃紺・黒・グレーから、白・ベージュ・デニム、淡い緑と青へ。完成ポートレートではなく「動作途中」。短文。過度な性的演出はしない。</p><div class="notice">AI GENERATED / FICTIONAL CHARACTER<br>プロフィール・販売ページなど誤認が起きやすい場所で表示します。</div></section><section class="card"><p class="eyebrow">X PROFILE · DAY 0</p><p><b>あおば｜帰宅後の記録</b><br>仕事終わりの、何でもない写真。<br>AI generated / fictional character</p><button class="secondary" data-go="posts">固定投稿と初期投稿を見る</button></section>`;}
function posts(){return header('ポストと投稿キュー','生成 → キャラ確認 → 人の承認 → Xへ渡す。')+drawer()+`<button class="primary" data-go="create">＋ 新しい投稿を作る</button><div class="segmented"><button class="active">投稿キュー</button><button data-go="analytics">反応を見る</button></div>${state.posts.map((p,i)=>`<article class="card post"><p class="eyebrow">${esc(p.purpose)}</p><p>${esc(p.text)}</p><div class="post-meta">${esc(p.time)}　·　${esc(p.type)}　·　<span class="queue-status ${p.status}">${p.status==='approval'?'承認待ち':p.status==='published'?'公開済み':'下書き'}</span></div>${p.status!=='published'?`<button class="secondary" data-share="${i}">Xで下書きを開く</button>`:''}</article>`).join('')}`;}
function create(){const v=visualPrompts[state.visualVariant%visualPrompts.length];return header('投稿を作る','反応分析から、次に生成すべき画像まで提案します。')+drawer()+`<section class="card"><p class="eyebrow">POST BRIEF</p><div class="bar-row"><b>目的</b><span>認知 → ファン化</span><span></span></div><div class="bar-row"><b>タイプ</b><span>日常・帰宅後</span><span></span></div><div class="bar-row"><b>物語</b><span>見られることが嬉しい</span><span></span></div><p class="sub">AIスコア：スクロール停止 82／キャラ整合 94／物語 87</p></section><section class="card"><p class="eyebrow">IMAGE RECOMMENDATION</p><div class="prompt-head"><b>${v.title}</b><button class="tiny-button" data-action="next-visual">別案を出す</button></div><p class="callout">${v.reason}</p><div class="prompt-head"><p class="eyebrow" style="margin:12px 0 0">日本語プロンプト</p><button class="tiny-button" data-action="copy-prompt">コピー</button></div><div class="prompt-box" id="visual-prompt">${v.text}</div><p class="hint">画像生成サービスへ貼り付ける前に、顔・髪・服装・物語との矛盾を確認します。</p></section><section class="card"><div class="field"><label for="text">本文</label><textarea id="text">やっと帰宅。\n今日、思ったより長かった。</textarea><p class="hint">説明しすぎない。あおば自身が書きそうな短さで。</p></div><div class="field"><label for="time">投稿予定</label><input id="time" value="今夜 20:30" /></div><button class="primary" id="save-post">承認待ちへ保存</button></section>`;}
function schedule(){const days=['月','火','水','木','金','土','日'];return header('週間スケジュール','投稿が生活や物語と矛盾しないように組みます。')+drawer()+`<section class="card"><p class="eyebrow">WEEK PLAN</p>${days.map((d,i)=>`<button class="list-link" data-go="${i===3?'create':'posts'}"><span><b>${d}曜 ${i===3?'· 今日':''}</b><small>${['通勤の一言','残業帰り','投稿なし','髪をほどく途中','コンビニのプリン','白シャツとデニム','外で笑う'][i]}</small></span><span class="badge">${i===3?'作成':'予定'}</span></button>`).join('')}</section>`;}
function engage(){return header('交流','スパム化せず、関係が育つ会話だけを人が選びます。')+drawer()+`<section class="card"><p class="eyebrow">INBOUND · REPLY SUGGESTION</p><b>@sample_user</b><p class="sub">「こういう雰囲気好き」</p><div class="advice">返信案：<b>「ありがとうございます。自分ではあんまり分からないです。」</b><br>短く受け取り、会話を無理に引き延ばさない。</div><button class="secondary" data-action="reply">返信文をコピー</button></section><section class="card"><p class="eyebrow">OUTBOUND · PROSPECTS</p><p class="sub">日常・写真・仕事の話題が重なるアカウントを10件まで候補化。送信は手動です。</p><button class="secondary" data-action="prospects">候補の見方</button></section>`;}
function monetize(){return header('note・販売','反応が積み上がってから、役に立つ形へ変換します。')+drawer()+`<section class="card"><p class="eyebrow">PHASE 04 · LOCKED</p><b>今は売らない。</b><p class="sub">販売は、認知とファン化が十分に育ち、実際の質問・反応に需要が現れた時だけ開放します。</p></section><section class="card"><p class="eyebrow">FUTURE PRODUCT SIGNAL</p><p class="sub">「画像をどう作っているの？」という質問が増えたら、画像生成・自然に見せるための記録をnote候補にします。実績や体験は捏造しません。</p><button class="secondary" data-go="analytics">需要シグナルを見る</button></section>`;}
function analytics(){return header('分析 → 改善','数字で終わらせず、次に生成すべき画像を決めます。')+drawer()+`<section class="card"><p class="eyebrow">WHAT WORKED · WEEK 3</p><div class="bar-row"><b>仕事帰り</b><div class="bar"><i style="width:88%"></i></div><span>◎</span></div><div class="bar-row"><b>全身が分かる写真</b><div class="bar"><i style="width:78%"></i></div><span>○</span></div><div class="bar-row"><b>少し崩れた髪</b><div class="bar"><i style="width:84%"></i></div><span>◎</span></div><div class="bar-row"><b>自然な室内光</b><div class="bar"><i style="width:71%"></i></div><span>○</span></div><div class="bar-row"><b>説明的な長文</b><div class="bar"><i style="width:28%"></i></div><span>×</span></div></section><section class="card"><p class="eyebrow">NEXT IMAGE DECISION</p><p class="callout">次は「帰宅直後・全身が少し分かる・髪をほどく途中」。仕事帰りの文脈を残し、室内の構図で既視感を避けます。</p><button class="primary" data-go="create">日本語プロンプトを見る</button></section><section class="card"><p class="eyebrow">ONE CHANGE ONLY</p><p class="sub">来週は「仕事帰り＋短文」を3本残し、休日の白シャツ投稿を1本だけテストします。</p><button class="secondary" data-action="apply">来週の予定に反映</button></section>`;}
function guide(){return header('設計指針','このアプリが守る運用の基準です。')+drawer()+`<section class="card"><p class="eyebrow">CORE</p><p class="sub">強いキャラクター × 強い物語。画像だけを量産しない。現在のフェーズに合う次の一手をAIが提案し、人が承認する。</p></section><section class="card"><p class="eyebrow">AUTOMATION</p><p class="sub">生成・分析は${state.automation}。Xへの公開、返信送信、戦略変更は人が最終判断します。</p><div class="segmented">${['MANUAL','ASSIST','AUTO'].map(x=>`<button class="${state.automation===x?'active':''}" data-auto="${x}">${x}</button>`).join('')}</div></section><section class="card"><p class="eyebrow">CHECKLIST</p><p class="sub">反応が弱い時は、一度に全部変えません。アプローチ先／文／プロフィールの魅力／世界観の一貫性／フォロー理由を、1つずつ検証します。</p></section>`;}
function chat(){return header('AI Operator','相談から、投稿・予定・分析の画面へつなげます。')+drawer()+`<section class="chat">${state.messages.map(m=>`<div class="bubble ${m.from==='bot'?'bot':'me'}">${esc(m.text)}</div>`).join('')}<div class="suggestions"><button data-prompt="今日なに投稿すればいい？">今日なに投稿すればいい？</button><button data-prompt="キャラ、最近ブレてない？">キャラ、最近ブレてない？</button><button data-prompt="いつ販売を始める？">いつ販売を始める？</button></div><form class="chat-form" id="chat-form"><input id="chat-input" placeholder="運用AIに相談する" aria-label="運用AIに相談する"/><button>↑</button></form></section>`;}
function nav(){const tabs=[['home','⌂','ホーム'],['progress','◌','進捗'],['create','＋','投稿'],['posts','▤','キュー'],['chat','✦','AI']];return `<nav class="nav">${tabs.map(t=>`<button class="${state.tab===t[0]?'active':''} ${t[0]==='create'?'plus':''}" data-go="${t[0]}"><span>${t[1]}</span>${t[0]==='create'?'':`<small>${t[2]}</small>`}</button>`).join('')}</nav>`;}
function answer(q){if(q.includes('ブレ')) return '大きくはブレていません。いまは仕事帰りの反応が強いので、その延長で休日の白シャツ・スニーカーを1本だけ入れると、職場と私生活の両方があおばだと伝わります。';if(q.includes('販売'))return 'まだ始めません。販売の前に、質問・保存・継続して見に来る人が増えているかを確認します。商品は、実際の反応から決めます。';return '今日は帰宅後の短い投稿がおすすめです。写真は髪をほどく途中か、パンプスを脱いだ直後。文章は「やっと帰宅。」くらいで十分です。投稿画面に下書きを作りますか？';}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.go;state.drawer=false;render();});document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.task);state.completed=state.completed.includes(i)?state.completed.filter(x=>x!==i):[...state.completed,i];render();});document.querySelectorAll('[data-auto]').forEach(b=>b.onclick=()=>{state.automation=b.dataset.auto;render();});document.querySelector('[data-action="drawer"]')?.addEventListener('click',()=>{state.drawer=!state.drawer;render();});document.querySelector('[data-action="next-visual"]')?.addEventListener('click',()=>{state.visualVariant=(state.visualVariant+1)%visualPrompts.length;render();});document.querySelector('[data-action="copy-prompt"]')?.addEventListener('click',()=>copyText(visualPrompts[state.visualVariant%visualPrompts.length].text));document.querySelector('#save-post')?.addEventListener('click',()=>{state.posts.unshift({text:document.querySelector('#text').value,purpose:'DAY '+state.day+'｜認知をファン化へつなぐ',time:document.querySelector('#time').value,status:'approval',type:'日常'});state.tab='posts';render();});document.querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>{const p=state.posts[Number(b.dataset.share)];window.open('https://x.com/intent/post?text='+encodeURIComponent(p.text),'_blank','noopener');});document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{state.messages.push({from:'me',text:b.dataset.prompt},{from:'bot',text:answer(b.dataset.prompt)});render();});document.querySelector('#chat-form')?.addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#chat-input');if(!input.value.trim())return;const q=input.value.trim();state.messages.push({from:'me',text:q},{from:'bot',text:answer(q)});render();});document.querySelector('[data-action="reply"]')?.addEventListener('click',()=>copyText('ありがとうございます。自分ではあんまり分からないです。'));document.querySelector('[data-action="apply"]')?.addEventListener('click',()=>{state.tab='schedule';render();});}
function render(){const page=({home,progress,character,posts,create,schedule,engage,monetize,analytics,guide,chat}[state.tab]||home)();document.querySelector('#app').innerHTML=page+nav();bind();save();}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
